config/routes.rb
Rails.application.routes.draw do
  resources :questions
  root "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Mdpreview
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  body
    = yield

app/views/questions/_form.html.slim
#e-app
  = form_with(model: question, local: true) do |f|
    - if question.errors.any?
      #error_explanation
        h2
          = pluralize(question.errors.count, "error")
          |  prohibited this question from being saved:
        ul
          - question.errors.full_messages.each do |message|
            li
              = message
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :text
      = f.text_area :text, "v-model" => "originalText"
    .actions
      = f.submit

  .markdownPreview style="white-space: pre-wrap" v-html="markedText"    

javascript:
  var question =  #{@question.to_json.html_safe}

= javascript_pack_tag 'hello_vue'

app/views/questions/edit.html.slim
h1
  | Editing Question
= render 'form', question: @question
= link_to 'Show', @question
|  | 
= link_to 'Back', questions_path

app/views/questions/index.html.slim
p#notice
  = notice
h1
  | Questions
table
  thead
    tr
      th
        | Title
      th
        | Text
      th[colspan="3"]
  tbody
    - @questions.each do |question|
      tr
        td
          = question.title
        td
          = question.text
        td
          = link_to 'Show', question
        td
          = link_to 'Edit', edit_question_path(question)
        td
          = link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Question', new_question_path

app/views/questions/new.html.slim
h1
  | New Question
= render 'form', question: @question
= link_to 'Back', questions_path

app/views/questions/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @question.title
p
  strong
    | Text:
  = @question.text
= link_to 'Edit', edit_question_path(@question)
|  | 
= link_to 'Back', questions_path